# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_number', models.IntegerField(primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
